### ISSUE TITLE
The `readOnly` option is not respected for non-input tags (`contenteditable` is always set to `true`)

### ISSUE THREAD

**Issue by GitzJoey** [autoNumeric/vue-autoNumeric#14] opened 2018-05-04 17:28 UTC
hi,
i'm having a problem when i set to readOnly with currency symbol on it
there's red underline on the text
![capture](https://user-images.githubusercontent.com/5994569/39642218-2595d4f4-4ffb-11e8-864d-e70c2cce5811.PNG)

how to set it to false?

**Comment by AlexandreBonneau** [comment] 2018-05-08 00:10
Hey @GitzJoey, I created a [codepen](https://codepen.io/AnotherLinuxUser/pen/QrOYga?editors=1010) to reproduce your problem, however currently the `readOnly` option is only used so set the `<input>` element to read-only mode, not the other tags.

I guess I could modify AutoNumeric so that when using non-input tags and the `readOnly` option, the `contenteditable` attribute would be set to `false`.

**Comment by GitzJoey** [comment] 2018-05-09 04:51
yes, the common sense is if read only it should be non editable. anyway thanks very much for fast response.

**Comment by AlexandreBonneau** [comment] 2018-05-23 21:10
This is fixed in AutoNumeric `v4.2.13`

**Comment by AlexandreBonneau** [comment] 2018-05-25 01:55
The component needs a little bit of work too since we currently force the `contenteditable` prop to true when a non-input tag is detected.

**Comment by AlexandreBonneau** [comment] 2018-05-25 19:55
Fixed in `v1.2.5`

**Closed** 2018-05-25 19:54 UTC
Labels: Feature request
